### ISSUE TITLE
структурировать фронтенд

### ISSUE THREAD

**Issue by demosglok** [horba/pineapple#1]
Структурировать фронтенд:
 - выделить стили в отдельный файл wwwroot/css/styles.css
 - добавить хедер, футер и центральную часть (лучше через flex)
 - центральную часть разбить на 3 части - левую, центральную и правую. твиты оставить в центральной

**Comment by horba** [comment]
соотношение левой - центральной - правой части -> 1 : 3 : 1

материалы по флексам:
http://html5.by/blog/flexbox/

**Comment by horba** [comment]
Здравствуйте. Заметила, что вы взяли следующую задачу с беклога. Напоминаю, что это возможно только после того, как вы выполните текущие задачи из первого спринта. Если же вы закончили работу по какой-то из задач, то, пожалуйста, отправьте пулл реквест с ветки, в которой находится реализация функционала, в ветку develop и заасаньте меня и Дмитрия. К сожалению, задача не может считаться выполненной, пока вы не сделаете, как минимум, пулл реквест.
Если у вас возникли трудности с созданием пулл реквеста, вы можете задать нам вопрос о возникших трудностях и мы постараемся вам помочь.
