### ISSUE TITLE
добавить в бекенде в контроллер метод для добавления твита

### ISSUE THREAD

**Issue by demosglok** [horba/pineapple#2]
В контроллере TweetsController добавить метод для добавления нового твита
пока его не нужно никуда сохранять.

**Comment by horba** [comment]
Здравствуйте. Заметила, что вы взяли следующую задачу с беклога. Напоминаю, что это возможно только после того, как вы выполните текущие задачи из первого спринта. Если же вы закончили работу по какой-то из задач, то, пожалуйста, отправьте пулл реквест с ветки, в которой находится реализация функционала, в ветку develop и заасаньте меня и Дмитрия. К сожалению, задача не может считаться выполненной, пока вы не сделаете, как минимум, пулл реквест.
Если у вас возникли трудности с созданием пулл реквеста, вы можете задать нам вопрос о возникших трудностях и мы постараемся вам помочь

**Comment by Markiz9999** [comment]
У нас в develop в TweetsController уже есть следующий кусок кода, который судя по всему и есть решением данной задачи. Данную таску отметить как закрытая?
`// POST api/values
        [HttpPost]
        public void Post([FromBody]string value)
        {
            TweetsService modelReader = new TweetsService();
            modelReader.AddTweet(value);
        }`
