### ISSUE TITLE
Добавить стилизацию для страницы с твиттами

### ISSUE THREAD

**Issue by horba** [horba/pineapple#24]
Нужно сделать наше приложение красивее :)

1. продумать мокапы (схематическое размещение основных элементов страницы) для страницы твиттов.
2. выбрать цветовую палитру.
3. Сверстать и стилизовать страницу в соответствии с утвержденным мокапом и палитрой.

**Comment by OllyV** [comment]
https://ninjamock.com/s/9R8GKWx
