### ISSUE TITLE
Folowers

### ISSUE THREAD

**Issue by horba** [horba/pineapple#25]
Необходимо:

- [ ] организация хранения данных в базе и взаимосвязь с другими данными;
- [ ]  добавить FollowersService с двумя методами Follow(currentUser, targetUser) и UnFollow(currentUser, targetUser) который будет отвечать за фоловеров.
- [ ] добавить модельку для фоловеров;
- [ ] написать миграцию для внесенных в бд изменений.

**Comment by demosglok** [comment]
на первом этапе, если таблицы Users нет можно
1) проработать прототип и скелет сервиса
2) сделать свою таблицу для хранения фоловеров. у тебя там будет только одно поле для связи с юзерами user_id (миграцию тоже надо)
3) сделать работу с этой таблицей
