### ISSUE TITLE
слой для работы с БД

### ISSUE THREAD

**Issue by demosglok** [horba/pineapple#3]
Реализовать слой (термин из архитектуры ПО - набор классов и интерфейсов или класса и интерфейса) для работы с БД.
можно начать с интерфейса ITweetsService  с методами AddTweet(string), и GetTweets(int limit)
и его реализации. 
пока что предполагаем что все твиты состоят из текста (строки) и даты. все анонимные, без привязки юзеров и выдается N последних твитов для показывания
В сервисе предусмотреть подключение к реальной БД или (если сходу не вышло) просто работать с текстовым файл (append'ов добавлять строчку и Read'ом выбирать все записи и из них брать N последних) 

Подключение к БД и прочие архитектурные вопросы не стесняйтесь спрашивать

**Comment by OllyV** [comment]
Поставила SQLserver2014, более поздние на windows7 не стали. Удалось запустить сервер и создать базу данных. Также удалось подключиться из VS13. Не могу подключиться из VS17.

**Comment by demosglok** [comment]
fа как именно пытаетесь из VS17 подключится и где начинаются проблемы?

**Comment by horba** [comment]
Здравствуйте. Данный вопрос не касается бизнес логики задачи. Прошу перенести обсуждение на форум :)
