### ISSUE TITLE
лента из новостей фоловеров

### ISSUE THREAD

**Issue by demosglok** [horba/pineapple#34]
после реализации задач 25 и 32 реализовать ленту новостей (твитов) не из всех подряд твитов, а только из твитов тех пользователей, на которых подписан текущий пользователь. 
твиты в ленте ограничить только последними 2мя сутками

Также связана с #51 и  #52

**Comment by FoxCaptainFox** [comment]
Таск включает и фронтендовую часть, и бэкендовую?

**Comment by horba** [comment]
Да
