### ISSUE TITLE
Добавление и вычитка твитов из бд

### ISSUE THREAD

**Issue by demosglok** [horba/pineapple#4]
Если реализована задача #3 , реализовать запись и чтение твитов из БД.

**Comment by FoxCaptainFox** [comment]
В чём именно заключается задание?
Я так понимаю, нужно в JS написать вызов БД, чтобы вывести или ввести твиты в неё?

**Comment by demosglok** [comment]
взять тот сервис, который реализован в задаче #3 и работает с простым файлом вместо записи и чтения из базы данных и переделать его так, что б запись и чтение твитов происходили в базу данных, а не в файл. параллельно создать миграцию (смотри таску на мигратор) по добавлению в создании в базе нужной таблички "твиты" с нужными колонками.
